<a href="https://colab.research.google.com/github/aaronds09/test_cvia/blob/master/afp_prog_linear_alg_problemas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#Functions used
C=np.array([[6, -4, 1],
            [-4, 6,-4],
            [1, -4, 6]], dtype=np.float)
D=np.array([[-14, 36, 6],[22, -18, 7]], dtype=np.float)
E=np.array([-14, 36, 6], dtype=np.float)

#Computes the determinat of a matrix
def det(a):
  n=a.shape[0]
  ao=a.copy()
  for k in range(0,n-1):
    for i in range(k+1,n):
      if ao[i,k]!=0.0:
        lam=ao[i,k]/ao[k,k]
        ao[i,k:n]=ao[i,k:n]-lam*ao[k,k:n]
          
  bo=np.prod(np.diagonal(ao))
  return(bo.astype(np.float16))
  
#Evaluates the condition by determinant
def eval_condt(A):
  if det(A)==0:
    return(print('Det=0.0, Singular'))
  if det(A)<0.5:
    d=str(det(A))
    return(print(f'Det={d}, Ill conditioned'))
  if det(A)>0:
    d=str(det(A))
    return(print(f'Det={d}, Well conditioned'))

#Gauss for multiple systems
def gauss_mul(a,b):
  n=a.shape[0]
  m=b.shape[0]
  ao=a.copy()
  bo=b.copy()
  for j in range(0,m):
    for k in range(0,n-1):
      for i in range(k+1,n):
        if ao[i,k]!=0.0:
          lam=ao[i,k]/ao[k,k]
          ao[i,k:n]=ao[i,k:n]-lam*ao[k,k:n]
          bo[0:m,i]=bo[0:m,i]-lam*bo[0:m,k]
          #print(a)
    for l in range(n-1,-1,-1):
      bo[j,l] = (bo[j,l] - np.dot(ao[l,l+1:n],bo[j,l+1:n]))/ao[l,l]

  return(bo.astype(np.float16))

#Gauss for singular system
def gauss_sim(a,b):
  n=a.shape[0]
  ao=a.copy()
  bo=b.copy()
  for k in range(0,n-1):
    for i in range(k+1,n):
      if ao[i,k]!=0.0:
        lam=ao[i,k]/ao[k,k]
        ao[i,k:n]=ao[i,k:n]-lam*ao[k,k:n]
        bo[i]=bo[i]-lam*bo[k]
          
  for l in range(n-1,-1,-1):
    bo[l] = (bo[l] - np.dot(ao[l,l+1:n],bo[l+1:n]))/ao[l,l]

  return(bo.astype(np.float16))

#Examples
print(gauss_mul(C,D))
print(gauss_sim(C,E))
print(det(C))


[[10. 22. 14.]
 [ 3. -1. -0.]]
[10. 22. 14.]
50.0


In [ ]:
#Problema 1:
A=np.array([[1, 2, 3],
            [2, 3, 4],
            [3, 4, 5]], dtype=np.float)
B=np.array([[2.11 , -0.80, 1.72],
            [-1.84,  3.03, 1.29],
            [-1.57,  5.25, 4.3]], dtype=np.float)
C=np.array([[2, -1, 0],
            [-1, 2,-1],
            [0, -1, 2]], dtype=np.float)
D=np.array([[4,   3, -1],
            [7,  -2,  3],
            [5, -18, 13]], dtype=np.float)
eval_condt(A)
eval_condt(B)
eval_condt(C)
eval_condt(D)




Det=0.0, Singular
Det=0.05887, Ill conditioned
Det=4.0, Well conditioned
Det=0.0, Singular


In [ ]:
#Problema 4:
A=np.array([[2,-3,-1],[3,2,-5],[2,4,-1]],dtype=np.float)
b=np.array([3, -9, 5], dtype=np.float)
print(gauss_sim(A,b))

#Problema 5:
A=np.array([[2,0,-1,0],[0,1,2,0],[-1,2,0, 1],[0,0,1,-2]],dtype=np.float)
B=np.array([[1,0,0,0],[0,0,1,0]], dtype=np.float)
print(gauss_mul(A,B))

#Problema 6:
A=np.array([[1,2,0,-2,0],[0,1,-1,1,-1],[0,1,0,2,-1],[0,0,2,1,2],[0,0,0,-1,1]],dtype=np.float)
b=np.array([-4,-1,1,1,-2], dtype=np.float)
Xo=gauss_sim(A,b)
X=np.array([Xo[3],Xo[2],Xo[0],Xo[4],Xo[1]])
print(X)

[4.12   0.2856 4.387 ]
[[ 0.4375  0.25   -0.125  -0.0625]
 [-0.125   0.5    -0.25   -0.125 ]]
[ 1.  1.  2. -1. -2.]
